os: linux
dist: bionic    # Ubuntu 18.04 LTS
language: ruby

# Clone full git history for git-restore-mtime to work
git:
  depth: false

# Install the necessary software
addons:
  apt:
    packages:
    - inkscape
    - pdf2svg

before_install:
  - git clone https://github.com/MestreLion/git-tools # Distro version is currently broken

script: 
  - ./git-tools/git-restore-mtime
  - make check

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up installation of html-proofer

cache:
  bundler: true               # Enable caching of bundler gem packages
  directories:
  - $TRAVIS_BUILD_DIR/.cache  # Enable caching link checks
  - $TRAVIS_BUILD_DIR/assets/infographics  # Enable caching of generated infographics

deploy:
  provider: pages
  local_dir: _site
  target_branch: gh-pages
  skip_cleanup: true
  keep_history: false
  verbose: false
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
