# Site settings
title: Fakta o změně klimatu
email: info@faktaoklimatu.cz
author:
description: Veřejně dostupné infografiky o změně klimatu země
url: https://faktaoklimatu.cz
contact: info@faktaoklimatu.cz

# Build settings
exclude: [ "Gemfile", "Gemfile.lock", "Makefile"    # Build settings
         , "README.md", "utils"                     # Development files
         , "_infografiky/*/*.pdf"                   # Original infographics (build moves them to assets)
         , "_studie/*.jpg"                          # Study images
         ]
collections:
    infografiky:
        output: true
        permalink: /:collection/:title
    sekce:
        output: false
        permalink: /:collection/:title
    stranky:
        output: true
        permalink: /:title
    studie:
        output: true
        permalink: /:collection/:title
sass:
    sass_dir: assets/css

cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    css_hash:         "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    js:               "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    js_hash:          "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    jquery:           "https://code.jquery.com/jquery-3.2.1.slim.min.js"
    jquery_hash:      "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    popper_hash:      "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
